;; This logfile was generated automatically by `xindy'
;; at 28.06.2023  19:24:57
;; Indexstyle: "H:\\Mi unidad\\Tesis_cevu\\Escritura_tesis\\Tesis Cevu\\aIgjr8RPoB", Rawindex: "H:\\Mi unidad\\Tesis_cevu\\Escritura_tesis\\Tesis Cevu\\uLuosw5kHo", Output: "template.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "»—" -> "M"
Letter-group: "——" -> "E"
Letter-group: "ÐÃ†" -> "S"
Letter-group: "ÐÃÊ†" -> "S"
Letter-group: "œ»Ë¨" -> "F"
Letter-group: "»—€" -> "M"
Letter-group: "´œÈ" -> "L"
Letter-group: "´ËÚ†" -> "L"
Letter-group: "œ€" -> "D"
Letter-group: "€†" -> "A"
Letter-group: "Ð†€" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "€†" -> "A"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ€" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "——" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ»Ë¨" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´œÈ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»—€" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ð†€" -> "S"
Reading raw-index "H:\\Mi unidad\\Tesis_cevu\\Escritura_tesis\\Tesis Cevu\\uLuosw5kHo"...WARNING: location-reference "{}{es@scroman  {ix}}" did not match any location-class! (ignored)
WARNING: location-reference "{}{es@scroman  {ix}}" did not match any location-class! (ignored)

makeglossaries diagnostic messages:

You may have forgotten to add a location 
class with \GlsAddXdyLocation or you may have 
the format incorrect or you may need 
the package option esclocations=true.
