;; This logfile was generated automatically by `xindy'
;; at 15.04.2023  18:02:24
;; Indexstyle: "/tmp/5KfqMjdf5x", Rawindex: "/tmp/oQ9qbfyOkr", Output: "template.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "»—" -> "M"
Letter-group: "——" -> "E"
Letter-group: "ÐÃ†" -> "S"
Letter-group: "ÐÃÊ†" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "——" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»—" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÃ†" -> "S"