;; This logfile was generated automatically by `xindy'
;; at 11.05.2023  20:35:54
;; Indexstyle: "/tmp/KEmeVARQo5", Rawindex: "/tmp/tdLNk01xY2", Output: "template.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "»—" -> "M"
Letter-group: "——" -> "E"
Letter-group: "ÐÃ†" -> "S"
Letter-group: "ÐÃÊ†" -> "S"
Letter-group: "œ»Ë¨" -> "F"
Letter-group: "»—€" -> "M"
Letter-group: "´œÈ" -> "L"
Letter-group: "´ËÚ†" -> "L"
Letter-group: "œ€" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ€" -> "D"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "——" -> "E"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "œ»Ë¨" -> "F"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´œÈ" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "»—€" -> "M"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "ÐÃ†" -> "S"